### ISSUE TITLE
pip3 install matplotlib-3.6.2-cp311-cp311-win_arm64.whl Error

### ISSUE THREAD

**Issue by xiaomeixw** [cgohlke/win_arm64-wheels#3]
Processing c:\users\xiong\downloads\2022.11.12-experimental-cp311-win_arm64.whl\2022.11.12-experimental-cp311-win_arm64.whl\matplotlib-3.6.2-cp311-cp311-win_arm64.whl
Collecting contourpy>=1.0.1 (from matplotlib==3.6.2)
  Using cached contourpy-1.1.0.tar.gz (13.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0 C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0\.mesonpy-pyf611ee\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0\.mesonpy-pyf611ee\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.1.1
      Source dir: C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0
      Build dir: C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0\.mesonpy-pyf611ee\build
      Build type: native build
      Project name: contourpy
      Project version: 1.1.0

      ..\..\meson.build:1:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      A full log can be found at C:\Users\Xiong\AppData\Local\Temp\pip-install-7046wxb8\contourpy_903c80e30d234c24b2cb83f0374b0ef0\.mesonpy-pyf611ee\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xiaomeixw** [comment]
2022.11.12-experimental-cp311-win_arm64.whl

**Comment by cgohlke** [comment]
All dependencies for matplotlib are included in the releases. Refer to https://pip.pypa.io/en/stable/cli/pip_install/ for pip options, e.g., `--no-deps --pre --no-index --find-links`.

**Comment by xiaomeixw** [comment]
let me use [2023.4.1-experimental-cp311-win_arm64.whl.zip] try again
[matplotlib](https://pypi.org/project/matplotlib/) 3.7.1
I will give you feedback later.

**Comment by xiaomeixw** [comment]
I know why！！！
should install numpy.whl first，then install contourpy.whl， then install kiwisolver.whl And finally install matplotlib.whl
-----------------------------------------------------------------------
Package         Version
--------------- -------
contourpy       1.0.7
cycler          0.11.0
fonttools       4.40.0
kiwisolver      1.4.4
matplotlib      3.7.1
numpy           1.24.2
packaging       23.1
Pillow          9.5.0
pip             23.1.2
pyparsing       3.1.0
python-dateutil 2.8.2
setuptools      65.5.0
six             1.16.0
wheel           0.40.0

**Comment by xiaomeixw** [comment]
Thanks again

**Comment by Jakelamers64** [comment]
Where can one find the kiwisolver.whl compatible with win arm64?

**Comment by cgohlke** [comment]
> Where can one find the kiwisolver.whl compatible with win arm64?

[v2023.9.30](https://github.com/cgohlke/win_arm64-wheels/releases/tag/v2023.9.30)
